name = "wsu-invoice-generator"
account_id = "7d181c0234e86356f5fe834b5978e300" # invoice.workers.dev
zone_id = "weshopu.us"
type = "webpack"
workers_dev = true
main = "./index.js"
compatibility_date = "2024-10-30"
routes = [
  { pattern = "invoice-generator.weshopu.us", custom_domain = true }
]